name: aeduin-rl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch==1.7.1
  - pip
  - python==3.9.1
  - pip:
      - numpy==1.20.1
      - argparse
      - matplotlib
      - scipy
      - nose
